name: Build Android APK
on:
  push:
    branches: [ main ]  # Se activa cada vez que subes algo a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flet
          # Si creaste el requirements.txt, también lo leerá:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build APK
        run: |
          # Aquí le decimos que use tu icono de la carpeta assets
          flet build apk --project "Scaffold Cwsis n.v" --icon assets/icon.png

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/apk/*.apk
