name: Build Flet APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flet

      - name: Build APK
        run: |
          # Cambiamos la forma de llamar al icono para que la versión 0.82.0 no de error
          flet build apk --project "Mi Almacén" --product "Mi Almacen" --icon "./icono.png"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi_Almacen_App
          path: build/apk/*.apk
